/**
 * Generate the screenshot wall in both READMEs from each skin's skin.json and preview/.
 *
 * A hand-written index of dozens of entries inevitably drifts (edit a tagline or add a skin and the sync is forgotten),
 * so this section is always generated by the script, and CI can check in passing that it is up to date.
 *
 * Two walls, one source: README.md takes `nameEn` / `taglineEn` and README.zh-CN.md takes `name` / `tagline`.
 * Keeping both in one script is what stops the translations from drifting apart.
 *
 * Usage: node scripts/readme.mjs
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const BEGIN = '<!-- SKINS:BEGIN -->'
const END = '<!-- SKINS:END -->'
const COLUMNS = 3

const rows = []
for (const name of readdirSync('packages', { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort()) {
  const dir = join('packages', name)
  const skin = JSON.parse(readFileSync(join(dir, 'skin.json'), 'utf8'))
  const previewDir = join(dir, 'preview')
  const shot = existsSync(previewDir)
    ? readdirSync(previewDir).find((f) => /\.(webp|png|jpg|jpeg)$/i.test(f))
    : undefined
  rows.push({ name, skin, image: shot ? `${dir}/preview/${shot}` : undefined })
}

/** The two language variants. `lang.note` is the generated-section warning, in that language. */
const LANGS = [
  {
    file: 'README.md',
    title: (skin) => skin.nameEn ?? skin.name,
    tagline: (skin) => skin.taglineEn ?? skin.tagline ?? '',
    scheme: { light: 'light', dark: 'dark' },
    note: (n) => `<sub>${n} skins. This section is generated by \`scripts/readme.mjs\` — do not edit by hand.</sub>`,
  },
  {
    file: 'README.zh-CN.md',
    title: (skin) => skin.name,
    tagline: (skin) => skin.tagline ?? '',
    scheme: { light: '浅色', dark: '暗色' },
    note: (n) => `<sub>共 ${n} 套皮肤，本段由 \`scripts/readme.mjs\` 生成，请勿手改。</sub>`,
  },
]

for (const lang of LANGS) {
  const cells = rows.map(({ name, skin, image }) => {
    const title = `<b>${lang.title(skin)}</b>`
    const scheme = lang.scheme[skin.colorScheme] ?? ''
    const img = image
      ? `<a href="packages/${name}"><img src="${image}" alt="${lang.title(skin)}" width="100%"></a><br>`
      : ''
    return [
      '<td width="33%" valign="top">',
      `${img}${title}${scheme ? ` <sub>${scheme}</sub>` : ''}<br>`,
      `<sub>${lang.tagline(skin)}</sub><br>`,
      `<sub><code>packages/${name}</code></sub>`,
      '</td>',
    ].join('\n')
  })

  const table = ['<table>']
  for (let i = 0; i < cells.length; i += COLUMNS) {
    table.push('<tr>')
    table.push(...cells.slice(i, i + COLUMNS))
    table.push('</tr>')
  }
  table.push('</table>')

  const section = [BEGIN, lang.note(rows.length), '', ...table, END].join('\n')

  let readme = readFileSync(lang.file, 'utf8')

  // Update the count in the badge while we are here. A hardcoded number goes stale the moment a skin is added —
  // and this script has already counted them, so there is no reason for the two to disagree.
  readme = readme
    .replace(/badge\/skins-\d+-/, `badge/skins-${rows.length}-`)
    .replace(/alt="\d+ skins"/, `alt="${rows.length} skins"`)

  const start = readme.indexOf(BEGIN)
  const stop = readme.indexOf(END)
  if (start < 0 || stop < 0) {
    console.error(`Cannot find the ${BEGIN} / ${END} markers in ${lang.file}`)
    process.exit(1)
  }
  writeFileSync(lang.file, readme.slice(0, start) + section + readme.slice(stop + END.length))
  console.log(`✓ ${lang.file}: screenshot wall updated, ${rows.length} skins`)
}
